version: '3.1'

services:
  mysql:
    restart: always
    image: mariadb:11.4
    command: ['mariadbd','--character-set-server=utf8mb4']
    volumes:
    - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  openemr:
    restart: always
    image: openemr/openemr:7.0.3
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      OE_USER: ${OE_USER}
      OE_PASS: ${OE_PASS}
    depends_on:
    - mysql

  nginx:
    restart: always
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - certbot_certs:/etc/letsencrypt
    - certbot_www:/var/www/certbot
    depends_on:
    - openemr

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}
  certbot_certs: {}
  certbot_www: {}
