version: '3.1'

services:
  mysql:
    restart: always
    image: mariadb:11.4
    command: ['mariadbd','--character-set-server=utf8mb4']
    volumes:
    - databasevolume:/var/lib/mysql
    - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  openemr:
    restart: always
    image: openemr/openemr:7.0.3
    volumes:
    - logvolume01:/var/log
    - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      OE_USER: ${OE_USER}
      OE_PASS: ${OE_PASS}
    depends_on:
    - mysql

  nginx:
    restart: always
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/nginx-fallback.conf:/etc/nginx/nginx.conf:ro
    - ./ssl/openemr.crt:/etc/ssl/certs/openemr.crt:ro
    - ./ssl/openemr.key:/etc/ssl/private/openemr.key:ro
    - certbot_certs:/etc/letsencrypt
    - certbot_www:/var/www/certbot
    - ./nginx/health.html:/opt/health_status/health.html:ro # New mount for health.html
    depends_on:
    - openemr

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx

  php-fpm:
    image: php:8.2-fpm-alpine
    restart: always
    volumes:
      - ./php:/var/www/html

volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}
  certbot_certs: {}
  certbot_www: {}
