name: OpenEMR CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint Docker Compose file
      run: |
        docker-compose --env-file .env.example -f docker-compose.yml config

    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Lint setup script
      run: |
        shellcheck setup.sh update.sh backup.sh

    - name: Run smoke tests
      run: |
        docker-compose --env-file .env.example up -d
        sleep 30
        ./backup.sh
        curl -f http://localhost || (docker-compose logs; exit 1)
        docker-compose down
